"""Regenerate firestore.rules from round2.json (run after changing categories or quotas)."""
import json
from pathlib import Path

here = Path(__file__).parent
cfg = json.loads((here / "round2.json").read_text())
cats = cfg["categories"]

checks = "\n".join(
    f"        && catOk(d, '{c['key']}', {c['quota']}, {json.dumps(c['ids'])})" for c in cats
)
keys = json.dumps([c["key"] for c in cats])

rules = f"""rules_version = '2';
service cloud.firestore {{
  match /databases/{{database}}/documents {{
    // Round 1: one doc per product (P001..P104), one field per person: "yes" or "no".
    match /votes/{{pid}} {{
      allow read: if true;
      allow create, update: if pid.matches('P[0-9]{{3}}')
        && request.resource.data.keys().hasOnly(['Ali', 'Jibran', 'Ayan'])
        && request.resource.data.values().hasOnly(['yes', 'no']);
    }}

    // Round 2: one doc per person, one list of picked product ids per category.
    // Generated by make_rules.py from round2.json.
    function catOk(d, k, max, allowed) {{
      return !(k in d) || (d[k] is list && d[k].size() <= max && d[k].hasOnly(allowed));
    }}
    match /picks/{{person}} {{
      allow read: if true;
      allow create, update: if person in ['Ali', 'Jibran', 'Ayan']
        && request.resource.data.keys().hasOnly({keys})
        && isValid(request.resource.data);
    }}
    function isValid(d) {{
      return true
{checks};
    }}
  }}
}}
"""
(here / "firestore.rules").write_text(rules)
print("wrote firestore.rules")
